automation:
  scriptFailed: Não foi possível executar a automação
chart:
  createFailed: Não foi possível criar um gráfico
  deleteFailed: Não foi possível excluir este gráfico
  deleted: Gráfico excluído
  invalidConfig:
    missingDimensionsField: Campo de dimensões não definido
    missingDimensionsModifier: Modificador de dimensões não definido
    missingDimensionsSteps: As etapas de dimensões não estão definidas
    missingMetricsAggregate: Agregado de métricas não definido
    missingMetricsField: Campo de métricas não definido
    missingMetricsType: Tipo de gráfico de métricas não definido
    missingModuleID: Módulo não definido
    missingReports: Relatórios não definidos
  loadFailed: Não foi possível carregar o gráfico
  optionsBuildFailed: Não foi possível criar opções de gráfico
  saveFailed: Não foi possível salvar este gráfico
  saved: Gráfico salvo
  unsupportedRenderer: Renderizador não compatível
  colorScheme:
    fetch:
      failed: Falha ao buscar esquemas de cores personalizados
    create:
      success: Esquema de cores criado
      failed: Falha ao criar esquema de cores
    update:
      success: Esquema de cores atualizado
      failed: Falha ao atualizar o esquema de cores
    delete:
      success: Esquema de cores excluído
      failed: Falha ao excluir o esquema de cores
color:
  RGBA:
    invalid: Formato de cor RGBA inválido
field:
  missingRequired: Valor ausente no campo obrigatório
  unknownFieldKind: 'Erro: Tipo de campo desconhecido "{{kind}}", nenhum
    componente de visualização foi encontrado.'
  unsupportedKind: Tipo de campo não suportado {{kind}}
field-datetime:
  valueNotFuture: Valor passado no campo somente futuro
  valueNotPast: Valor futuro apenas no campo passado
field-geometry:
  geolocationErrors:
    permissionDenied: O usuário negou a solicitação de geolocalização
    positionUnavailable: As informações de localização não estão disponíveis
    timeout: A solicitação para obter a localização do usuário expirou
    unknownError: Ocorreu um erro desconhecido
    notSupported: A geolocalização não é suportada por este navegador
    errorOccurred: Ocorreu um erro ao obter a localização do usuário
    locationSearchFailed: Falha na pesquisa de local
general:
  composeAccessNotAllowed: Não é permitido acessar o Compose
  error: Erro
  success: Sucesso
  warning: Aviso
  info: Perceber
  import:
    failed: Falha na importação
    readingError: Erro ao ler o arquivo
    successful: Importação bem-sucedida
    typeMissmatch: 'Erro de importação: tentando importar objeto do tipo "{{type1}}"
      para uma lista de objetos do tipo "{{type2}}"'
list:
  load:
    error: Falha ao carregar a lista de recursos
module:
  created: Módulo criado
  createFailed: Não foi possível criar um módulo
  deleteFailed: Não foi possível excluir este módulo
  deleted: Módulo excluído
  saveFailed: Não foi possível salvar este módulo
  saved: Módulo salvo
  columns:
    saved: Colunas salvas
    saveFailed: Não foi possível salvar colunas
  recordPage:
    createFailed: Não foi possível criar a página de registro do módulo
  schemaAlterations:
    load:
      error: Não foi possível buscar alterações
    resolve:
      success: Alteração(ões) resolvida(s)
      error: Não foi possível resolver as alterações
    dismiss:
      success: Alteração dispensada
      error: Não foi possível descartar a alteração
namespace:
  application:
    createFailed: Não foi possível criar o aplicativo de namespace
    fetchFailed: Não foi possível buscar o aplicativo de namespace
    saveFailed: Não foi possível salvar o aplicativo de namespace
  assetUploadFailed: Não foi possível fazer upload dos recursos anexados
  createFailed: Não foi possível criar o namespace
  deleted: Namespace excluído
  deleteFailed: Não foi possível excluir este namespace
  disabled: Namespace desabilitado – redirecionando
  saveFailed: Não foi possível salvar este namespace
  saved: Namespace salvo
  cloneFailed: Não foi possível clonar este namespace
  imported: Namespace importado
  importFailed: Falha ao importar namespace
page:
  block:
    calendar:
      eventFetchFailed: Não foi possível buscar a lista de eventos
  createFailed: Não foi possível criar uma página
  cloneFailed: Não foi possível clonar esta página
  deleteFailed: Não foi possível excluir esta página
  iconFetchFailed: Não foi possível buscar a lista de ícones
  iconDeleteFailed: Não foi possível excluir o ícone selecionado
  iconDeleteSuccess: Ícone excluído
  loadFailed: Não foi possível carregar a árvore de páginas
  noPages: Nenhuma página encontrada
  saveFailed: Não foi possível salvar esta página
  saveFailedRequired: Não foi possível salvar esta página, todos os campos
    obrigatórios do módulo devem estar presentes
  saved: Página salva
  copySuccess: O bloco foi copiado com sucesso
  cloneSuccess: O bloco foi clonado no final da página
  pasteSuccess: O bloco foi colado na parte inferior da página
  duplicateFailed: Não foi possível duplicar o bloco
  blockWaiting: Há um bloco de página aguardando
  copyFailed: Não foi possível copiar o bloco de página {{reason}}
  invalidBlock: Não é um bloco de página válido
  page-layout:
    notFound:
      edit: Sem layout de página, crie um para editá-lo
      view: Nenhum layout de página encontrado. Crie um para visualizar a página
    save:
      success: Layout salvo
      failed: Falha ao salvar o layout
    clone:
      success: Layout clonado e selecionado
      failed: Falha ao clonar layout
    delete:
      success: Layout excluído
      failed: Falha ao excluir layout
record:
  createFailed: Não foi possível criar o registro
  createSuccess: Registro criado
  updateFailed: Não foi possível atualizar o registro
  updateSuccess: Registro atualizado
  deleteFailed: Não foi possível excluir o registro
  deleteSuccess: Registro excluído
  restoreFailed: Não foi possível restaurar o registro
  restoreSuccess: Registro restaurado
  deleteBulkFailed: Não foi possível excluir os registros selecionados
  deleteBulkRecordUpdateFailed: Não foi possível atualizar os registros selecionados
  deleteBulkSuccess: Registros selecionados excluídos com sucesso
  bulkRecordUpdateSuccess: Registros selecionados atualizados com sucesso
  restoreBulkFailed: Não foi possível restaurar os registros selecionados
  restoreBulkSuccess: Registros selecionados restaurados com sucesso
  invalidOwnerVar: Não é possível usar a variável ${ownerID} em páginas sem registro
  invalidRecordVar: Não é possível usar a variável ${record...} em páginas sem registro
  listLoadFailed: Não foi possível carregar a lista de registros
  loadFailed: Não foi possível carregar o registro
  countFailed: Falha ao buscar o número de registros disponíveis
  moduleMismatch: Módulo incompatível, módulo incompatível
  moduleNotDefined: Módulo de registro não definido
  moduleOrPageNotSet: "Erro de bloco RecordList: opção de módulo ou página não definida"
  unexpectedInput: A entrada inesperada para a propriedade de valores deve ser uma
    matriz com pares de objetos nome-valor
  unexpectedValue: Valor inesperado para módulo de registro ({{type}})
  validationErrors: verifique mensagens de erro no formulário
  validationWarnings: Registro salvo com sucesso, verifique mensagens de aviso no formulário
  staleDataRefresh: Dados de registro obsoletos, todas as alterações não salvas
    serão perdidas. Deseja atualizar os dados agora?
  fieldConditions:
    failed: Falha ao avaliar os campos condicionais do bloco de registros
record-list:
  corrupted-filter: Filtro corrompido
  corrupted-configured-fields: Colunas configuradas corrompidas
  incorrect-filter-structure: Estrutura incorreta do filtro {{filterID}}
report:
  listFetchFailed: Falha ao buscar relatórios
  fetchFailed: Falha ao buscar o relatório
  runFailed: Falha ao executar o relatório
translations:
  saved: Traduções salvas
  saveFailed: Não foi possível salvar as traduções
connection:
  read-failed: Falha ao ler a conexão
sensitivity-level:
  fetch-failed: Falha ao buscar níveis de sensibilidade
evaluate:
  failed: Falha ao avaliar a expressão
