errors:
  disabled: fluxo de trabalho ou gatilho desativado
  handleNotUnique: identificador de fluxo de trabalho não exclusivo
  invalidHandle: identificador inválido
  invalidID: ID inválido
  notAllowedToCreate: não tem permissão para criar fluxos de trabalho
  notAllowedToDelete: não é permitido excluir este fluxo de trabalho
  notAllowedToExecute: não tem permissão para executar este fluxo de trabalho
  notAllowedToExecuteCorredorStep: não é permitido executar a função corredorExec, corredor está desabilitado
  notAllowedToRead: não tem permissão para ler este fluxo de trabalho
  notAllowedToSearch: não tem permissão para pesquisar ou listar fluxos de trabalho
  notAllowedToUndelete: não é permitido cancelar a exclusão deste fluxo de trabalho
  notAllowedToUpdate: não tem permissão para atualizar este fluxo de trabalho
  notFound: fluxo de trabalho não encontrado
  staleData: dados obsoletos
  unknownWorkflowStep: etapa de fluxo de trabalho desconhecida
