configuration: Configuración
edge: Borde
label: Etiqueta *
target: Objetivo
tooltip:
  run-workflow: Ejecutar flujo de trabajo
  configure-step: Configurar paso
workflow:
  run-as: Ejecutar como
  not-setup-properly: Cuando no se establece explícitamente, el flujo de trabajo
    será ejecutado por el usuario que lo invocó.
  invalid-handle-characters: Debe tener al menos 2 caracteres. Sólo puede contener
    letras, números, guiones, guiones bajos y puntos. Debe terminar con letra o
    número
  placeholder-handle: identificador (a - z, 0 - 9, guión bajo, guión)
  sub-workflow:
    label: Subflujo de trabajo
    description: Los subflujos de trabajo no pueden tener activadores habilitados
