errors:
  invalidID: identificación no válida
  notAllowedToCreate: no se permite crear aplicaciones
  notAllowedToDelete: no se permite eliminar esta aplicación
  notAllowedToManageFlag: no se le permite administrar indicadores para aplicaciones
  notAllowedToManageFlagGlobal: no se le permite administrar indicadores globales para aplicaciones
  notAllowedToRead: No se permite leer esta aplicación.
  notAllowedToSearch: no se permite buscar o enumerar aplicaciones
  notAllowedToUndelete: No se permite recuperar esta aplicación.
  notAllowedToUpdate: no se permite actualizar esta aplicación
  notFound: aplicación no encontrada
